# Generated by Django 3.0.3 on 2020-08-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=30)),
                ('nachname', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=100)),
                ('postfach', models.IntegerField()),
                ('ort', models.CharField(max_length=100)),
                ('plz', models.IntegerField()),
                ('kanton', models.CharField(choices=[('SG', 'St.Gallen'), ('TG', 'Thurgau'), ('AI', 'Appenzell Innerrhoden'), ('AR', 'Appenzell Ausserrhoden'), ('ZH', 'Zürich'), ('BE', 'Bern'), ('UR', 'Uri'), ('SZ', 'Schwyz'), ('OW', 'Obwalden'), ('NW', 'Nidwalden'), ('GL', 'Glarus'), ('BL', 'Basel-Landschaft'), ('BS', 'Basel-Stadt'), ('SO', 'Solothurn'), ('FR', 'Freiburg'), ('ZG', 'Zug'), ('SH', 'Schaffhausen'), ('GR', 'Graubünden'), ('AG', 'Aargau'), ('JU', 'Jura'), ('GE', 'Genf'), ('NE', 'Neuenburg'), ('VS', 'Wallis'), ('VD', 'Waadt'), ('TI', 'Tessin')], max_length=15)),
                ('land', models.CharField(choices=[('CH', 'Schweiz'), ('AT', 'Österreich'), ('DE', 'Deutschland')], max_length=10)),
                ('geschlecht', models.CharField(choices=[('m', 'Herr'), ('f', 'Frau')], max_length=5)),
                ('title', models.CharField(choices=[('dr', 'Dr. '), ('prof', 'Prof. ')], max_length=5)),
                ('geburtsdatum', models.DateField()),
                ('age', models.IntegerField()),
                ('verwandte', models.CharField(max_length=100)),
                ('arztueberweisung', models.CharField(max_length=100)),
                ('email1', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=100)),
                ('erstellt', models.DateTimeField()),
                ('modifiziert', models.DateTimeField()),
                ('freifeld1', models.CharField(max_length=100)),
                ('freifeld2', models.CharField(max_length=100)),
                ('freifeld3', models.CharField(max_length=100)),
            ],
        ),
    ]
