# Generated by Django 3.1.1 on 2020-10-19 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anrede', models.CharField(default='Herr', max_length=10)),
                ('vorname', models.CharField(default='defaultname', max_length=30)),
                ('nachname', models.CharField(default='defaultname', max_length=30)),
                ('geburtstag', models.DateField(default=datetime.date(2020, 10, 19))),
                ('kanton', models.CharField(blank=True, choices=[('SG', 'St.Gallen'), ('TG', 'Thurgau'), ('AI', 'Appenzell Innerrhoden'), ('AR', 'Appenzell Ausserrhoden'), ('ZH', 'Zürich'), ('BE', 'Bern'), ('UR', 'Uri'), ('SZ', 'Schwyz'), ('OW', 'Obwalden'), ('NW', 'Nidwalden'), ('GL', 'Glarus'), ('BL', 'Basel-Landschaft'), ('BS', 'Basel-Stadt'), ('SO', 'Solothurn'), ('FR', 'Freiburg'), ('ZG', 'Zug'), ('SH', 'Schaffhausen'), ('GR', 'Graubünden'), ('AG', 'Aargau'), ('JU', 'Jura'), ('GE', 'Genf'), ('NE', 'Neuenburg'), ('VS', 'Wallis'), ('VD', 'Waadt'), ('TI', 'Tessin')], default='SG', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='http_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='state', max_length=10)),
                ('pid', models.CharField(default='pid', max_length=150)),
                ('name', models.CharField(default='defaultname', max_length=30)),
            ],
        ),
    ]
