# Generated by Django 3.1.1 on 2020-11-27 15:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anrede', models.CharField(default='Herr', max_length=10)),
                ('vorname', models.CharField(default='defaultname', max_length=30)),
                ('nachname', models.CharField(default='defaultname', max_length=30)),
                ('geburtstag', models.DateField(default=datetime.date(2020, 11, 27))),
                ('start', models.DateTimeField(default=datetime.datetime(2020, 11, 27, 16, 20, 9, 672157))),
                ('end', models.DateTimeField(default=datetime.datetime(2020, 11, 27, 16, 20, 9, 672157))),
                ('kanton', models.CharField(blank=True, choices=[('SG', 'St.Gallen'), ('TG', 'Thurgau'), ('AI', 'Appenzell Innerrhoden'), ('AR', 'Appenzell Ausserrhoden'), ('ZH', 'Zürich'), ('BE', 'Bern'), ('UR', 'Uri'), ('SZ', 'Schwyz'), ('OW', 'Obwalden'), ('NW', 'Nidwalden'), ('GL', 'Glarus'), ('BL', 'Basel-Landschaft'), ('BS', 'Basel-Stadt'), ('SO', 'Solothurn'), ('FR', 'Freiburg'), ('ZG', 'Zug'), ('SH', 'Schaffhausen'), ('GR', 'Graubünden'), ('AG', 'Aargau'), ('JU', 'Jura'), ('GE', 'Genf'), ('NE', 'Neuenburg'), ('VS', 'Wallis'), ('VD', 'Waadt'), ('TI', 'Tessin')], default='SG', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='http_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='state', max_length=10)),
                ('pid', models.CharField(default='pid', max_length=150)),
                ('name', models.CharField(default='defaultname', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billstate', models.CharField(max_length=30)),
                ('lastbill', models.DateTimeField(default=datetime.datetime(2020, 11, 27, 16, 20, 9, 672157))),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=30)),
                ('nachname', models.CharField(max_length=30)),
                ('birthday', models.DateField(default=datetime.date(2020, 11, 27))),
            ],
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Birthday', models.DateField(default=datetime.date(4501, 1, 1))),
                ('Gender', models.CharField(max_length=30)),
                ('Email1Address', models.CharField(max_length=30)),
                ('MailingAddressCity', models.CharField(max_length=30)),
                ('MailingAddressCountry', models.CharField(max_length=30)),
                ('MailingAddressPostalCode', models.CharField(max_length=30)),
                ('MailingAddressStreet', models.CharField(max_length=30)),
                ('GovernmentIDNumber', models.CharField(max_length=30)),
                ('Account', models.CharField(max_length=30)),
                ('MobileTelephoneNumber', models.CharField(default='NA', max_length=30)),
                ('syncstate', models.CharField(default='created', max_length=30)),
                ('lastsync', models.DateTimeField(default=datetime.datetime(4501, 1, 1, 0, 0))),
                ('CreationTime', models.DateTimeField(auto_now_add=True)),
                ('LastModificationTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=datetime.datetime(2020, 11, 27, 16, 20, 9, 672157))),
                ('lastbill', models.DateTimeField(default=datetime.datetime(2020, 11, 27, 16, 20, 9, 672157))),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='isys.invoice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='isys.patient')),
                ('tp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='isys.therapist')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='isys.patient'),
        ),
    ]
