# Generated by Django 3.0.3 on 2020-09-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummy',
            name='vorname',
            field=models.CharField(default='defaultname', max_length=30),
        ),
    ]
