# Generated by Django 3.0.3 on 2020-08-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='arztueberweisung',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='freifeld1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='freifeld2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='freifeld3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='geburtsdatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='geschlecht',
            field=models.CharField(choices=[('m', 'männlich'), ('f', 'weiblich')], max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='kanton',
            field=models.CharField(blank=True, choices=[('SG', 'St.Gallen'), ('TG', 'Thurgau'), ('AI', 'Appenzell Innerrhoden'), ('AR', 'Appenzell Ausserrhoden'), ('ZH', 'Zürich'), ('BE', 'Bern'), ('UR', 'Uri'), ('SZ', 'Schwyz'), ('OW', 'Obwalden'), ('NW', 'Nidwalden'), ('GL', 'Glarus'), ('BL', 'Basel-Landschaft'), ('BS', 'Basel-Stadt'), ('SO', 'Solothurn'), ('FR', 'Freiburg'), ('ZG', 'Zug'), ('SH', 'Schaffhausen'), ('GR', 'Graubünden'), ('AG', 'Aargau'), ('JU', 'Jura'), ('GE', 'Genf'), ('NE', 'Neuenburg'), ('VS', 'Wallis'), ('VD', 'Waadt'), ('TI', 'Tessin')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='plz',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='postfach',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telefon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='title',
            field=models.CharField(blank=True, choices=[('dr', 'Dr. '), ('prof', 'Prof. ')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='verwandte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
