# Generated by Django 3.1.1 on 2020-12-30 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 30, 20, 41, 1, 394025)),
        ),
        migrations.AlterField(
            model_name='dummy',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 30, 20, 41, 1, 394025)),
        ),
    ]
