# Generated by Django 3.1.1 on 2020-10-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isys', '0002_dummy_vorname'),
    ]

    operations = [
        migrations.CreateModel(
            name='http_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(default='defaultname', max_length=30)),
                ('nachname', models.CharField(default='defaultname', max_length=30)),
            ],
        ),
    ]
