# Generated by Django 3.1.1 on 2021-01-05 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isys', '0002_auto_20201230_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='lastsync',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='synclabel',
        ),
        migrations.AlterField(
            model_name='dummy',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 5, 12, 3, 56, 188859)),
        ),
        migrations.AlterField(
            model_name='dummy',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 5, 12, 3, 56, 188859)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='methods',
            field=models.ManyToManyField(blank=True, to='isys.Method'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='uploadfiles',
            field=models.ManyToManyField(blank=True, to='isys.Uploadfilepath'),
        ),
        migrations.AlterField(
            model_name='rechnung',
            name='mahnungen',
            field=models.ManyToManyField(blank=True, to='isys.Mahnung'),
        ),
        migrations.AlterField(
            model_name='rechnung',
            name='meetings',
            field=models.ManyToManyField(blank=True, to='isys.Meeting'),
        ),
    ]
