# Generated by Django 3.1.1 on 2020-11-27 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isys', '0002_auto_20201127_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 16, 44, 4, 213054)),
        ),
        migrations.AlterField(
            model_name='dummy',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 16, 44, 4, 213054)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='lastbill',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 16, 44, 4, 213054)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='lastbill',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 16, 44, 4, 213054)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 16, 44, 4, 213054)),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='Gender',
            field=models.CharField(choices=[('M', 'männlich'), ('W', 'weiblich')], default='M', max_length=30),
        ),
    ]
