# Generated by Django 3.1.1 on 2020-11-29 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isys', '0003_auto_20201127_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 16, 17, 40, 782457)),
        ),
        migrations.AlterField(
            model_name='dummy',
            name='geburtstag',
            field=models.DateField(default=datetime.date(2020, 11, 29)),
        ),
        migrations.AlterField(
            model_name='dummy',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 16, 17, 40, 782457)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='lastbill',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 16, 17, 40, 787457)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='lastbill',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 16, 17, 40, 788467)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 16, 17, 40, 787457)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 11, 29)),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='Gender',
            field=models.CharField(choices=[('1', 'weiblich'), ('2', 'männlich')], default='1', max_length=30),
        ),
    ]
