#from .patient import *
from .dummy import *
from .staff import *
from .patient import *
from .meeting import *
from .rechnung import *
from .location import *
from .method import *
from .buchung import *
from .bankkonto import *
from .habenkonto import *
from .sollkonto import *
from .mahnung import *
from .tarif import *
from .versicherung import *
from .uploadfilepath import *